aliases: []
creation_timestamp: 1701499817362
current_stage: None
description: null
last_updated_timestamp: 1701499817362
name: support_vector_regression_model
run_id: af67bf9b8e6d4374bb7e35966a85309e
run_link: null
source: /Users/tandavala/Documents/Trabalho/projecto_paralelo/modelo_preditivo_preco_residenciais/backend/file/140928785281970000/af67bf9b8e6d4374bb7e35966a85309e/artifacts/model
status: READY
status_message: null
storage_location: /Users/tandavala/Documents/Trabalho/projecto_paralelo/modelo_preditivo_preco_residenciais/backend/file/140928785281970000/af67bf9b8e6d4374bb7e35966a85309e/artifacts/model
user_id: null
version: 1
