aliases: []
creation_timestamp: 1701500065795
current_stage: None
description: null
last_updated_timestamp: 1701500065795
name: support_vector_regression_model
run_id: 57a8b55fcbb24b55bc3b15be65790a82
run_link: null
source: /Users/tandavala/Documents/Trabalho/projecto_paralelo/modelo_preditivo_preco_residenciais/backend/file/140928785281970000/57a8b55fcbb24b55bc3b15be65790a82/artifacts/model
status: READY
status_message: null
storage_location: /Users/tandavala/Documents/Trabalho/projecto_paralelo/modelo_preditivo_preco_residenciais/backend/file/140928785281970000/57a8b55fcbb24b55bc3b15be65790a82/artifacts/model
user_id: null
version: 3
