artifact_location: /Users/tandavala/Documents/Trabalho/projecto_paralelo/modelo_preditivo_preco_residenciais/backend/file/140928785281970000
creation_time: 1701499809564
experiment_id: '140928785281970000'
last_update_time: 1701499809564
lifecycle_stage: active
name: vitari_real_state
