artifact_location: /Users/tandavala/Documents/Trabalho/projecto_paralelo/modelo_preditivo_preco_residenciais/backend/file/0
creation_time: 1701499809533
experiment_id: '0'
last_update_time: 1701499809533
lifecycle_stage: active
name: Default
