artifact_uri: /Users/tandavala/Documents/Trabalho/projecto_paralelo/modelo_preditivo_preco_residenciais/backend/file/140928785281970000/af67bf9b8e6d4374bb7e35966a85309e/artifacts
end_time: 1701499817363
entry_point_name: ''
experiment_id: '140928785281970000'
lifecycle_stage: active
run_id: af67bf9b8e6d4374bb7e35966a85309e
run_name: support_vector_regression
run_uuid: af67bf9b8e6d4374bb7e35966a85309e
source_name: ''
source_type: 4
source_version: ''
start_time: 1701499809636
status: 3
tags: []
user_id: tandavala
